
name: Deployment on the DEV server
on:
  push: 
    branches:
      - main
jobs:
  ISSUANCE-DEV-DEPLOYMENT:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy Stack
        uses: easingthemes/ssh-deploy@main
        with:
          host: ${{ secrets.HOST_NAME_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.EC2_SSH_KEY_DEV }}
          port: ${{ secrets.PORT_DEV }}
          script: |
            echo "Connecting to ${{ secrets.HOST_NAME_DEV }} on port ${{ secrets.PORT_DEV }}"
            whoami
            cd ${{ secrets.TARGET_DEV_DIR }}
            if [ -f .env ]; then
            rm .env
            fi
            echo "${{ secrets.DEV_ENV }}" > .env
            ls -ltra
            ./deploy.sh
